
COMMIT_HASH=$(shell git rev-parse --short=8 HEAD 2>/dev/null)
BUILD_TIME=$(shell date +%FT%T%z)

COMMIT=$(shell git rev-parse HEAD 2>/dev/null)

VERSION_TAG = $(shell git describe --tags --exact-match 2>/dev/null | cut -f 1 -d '-' 2>/dev/null)

# If no git tag is set, fallback to 'DEVELOPMENT'
ifeq ($(strip ${VERSION_TAG}),)
VERSION_TAG := Development
endif
