name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v4
      with:
        name: libovpn-log-cert-expire-times
    - name: release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        artifacts: "ovpn-log-cert-expire-times.linux-amd64.tar.gz,sha256sum.txt"
        bodyFile: CHANGELOG.md
        allowUpdates: true
        removeArtifacts: true
